stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

build_backend:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t backend ./backend

build_frontend:
  stage: build
  image: node:22
  script:
    - cd frontend
    - npm install
    - npm run build

test_backend:
  stage: test
  image: python:3.12
  script:
    - cd backend
    - pip install -r requirements.txt
    - pytest || true
